### PR TITLE
Fixed: redirection to app after navigating to home screen and then logging in (#70)

### LINKED ISSUE #70: Unexpected URL redirect
## Current behavior

If the user navigates to login from an app and then:

1. Goes to homepage
2. returns to login screen
3. enters login credentials
4. Redirected to app they navigated to launchpad from

## Expected behavior

If the user exists the login flow and navigates to the Home Screen after which they return to the login page the redirect URL to the original app should be cleared from the state and the user should remain in launchpad.

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #70 

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

### CODE REVIEW

File: src/views/Home.vue [hunk 1]
```diff
@@ -86,6 +86,9 @@ export default defineComponent({
     IonLabel,
     IonPage
   },
+  ionViewDidEnter() {
+    this.authStore.setRedirectUrl('')
```
Comment (ymaheshwari1) [inline src/views/Home.vue:90]: Add comment

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]
